image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: prod

stages:
  - build
  - test
  - package
  - deploy

build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script: "mvn test"

docker-build:
  stage: package
  script:
    - docker build -t registry.gitlab.com/bolcom/junaid-subhani/mancala .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/bolcom/junaid-subhani/mancala
  only:
    - master

k8s-deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
    - echo "Deploying application..."
    - docker run -d --rm -p 8081:8081 registry.gitlab.com/bolcom/junaid-subhani/mancala
    - echo "Application successfully deployed."
  only:
    - master
